[package]
name = "idk2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
datetimeutils = "0.1.3"
slint = "1.4.0"

[build-dependencies]
slint-build = "1.4.0"
